import type { StageDef } from '@/types';

/**
 * All thirty campaign stages.
 *
 * XP is tuned against the level curve in the brief: the cumulative main-path XP
 * after stage s follows S(s) = 72.667s + 14s^2 + 1.333s^3, which lands a
 * main-path player on level 6 after stage 5, 11 after stage 10, 21 after stage
 * 20 and 30 by stage 29. Optional encounters accelerate this; the level 30 cap
 * is enforced in the progression system.
 *
 * Boss first-clear gold follows 80 + 35 * stageNumber exactly as specified, and
 * first-clear material bundles are sized against the settlement upgrade costs
 * (see tests/economy.test.ts, which simulates the whole campaign).
 */
export const STAGES: readonly StageDef[] = [
  {
    id: 1, region: 'farmland', nameKey: 'stage.1.name', objectiveKey: 'stage.1.objective',
    loreKey: 'stage.1.lore', bossKey: 'boss_gritch', bossNameKey: 'boss.boss_gritch.name', bossTestKey: 'stage.1.test',
    recommendedLevel: 1, chapterBoss: false,
    objective: { kind: 'rescue', count: 1, labelKey: 'stage.1.objective' },
    enemies: ['goblin_scout', 'orc_raider'],
    mapSeed: 1077, mapWidth: 45, mapHeight: 41,
    encounters: 4, caches: 2,
    firstClear: { gold: 115, wood: 11, stone: 0, iron: 0, shards: 0, xp: 58, ringId: 'ember' },
    replay: { gold: 46, wood: 6, stone: 0, iron: 0, shards: 0, xp: 25 },
    seasonRoute: { season: 'spring', noteKey: 'stage.route.1' },
    durationMinutes: [4, 6],
  },
  {
    id: 2, region: 'farmland', nameKey: 'stage.2.name', objectiveKey: 'stage.2.objective',
    loreKey: 'stage.2.lore', bossKey: 'boss_kruk', bossNameKey: 'boss.boss_kruk.name', bossTestKey: 'stage.2.test',
    recommendedLevel: 2, chapterBoss: false,
    objective: { kind: 'collect', count: 4, labelKey: 'stage.2.objective' },
    enemies: ['goblin_scout', 'goblin_archer', 'orc_raider'],
    mapSeed: 1154, mapWidth: 47, mapHeight: 42,
    encounters: 5, caches: 2,
    firstClear: { gold: 150, wood: 12, stone: 0, iron: 0, shards: 4, xp: 82, ringId: 'stoneward' },
    replay: { gold: 60, wood: 6, stone: 0, iron: 0, shards: 2, xp: 35 },
    seasonRoute: { season: 'summer', noteKey: 'stage.route.2' },
    durationMinutes: [4, 6],
  },
  {
    id: 3, region: 'farmland', nameKey: 'stage.3.name', objectiveKey: 'stage.3.objective',
    loreKey: 'stage.3.lore', bossKey: 'boss_bellwight', bossNameKey: 'boss.boss_bellwight.name', bossTestKey: 'stage.3.test',
    recommendedLevel: 3, chapterBoss: false,
    objective: { kind: 'destroy', count: 3, labelKey: 'stage.3.objective' },
    enemies: ['goblin_scout', 'barrow_wight', 'orc_raider'],
    mapSeed: 1231, mapWidth: 48, mapHeight: 44,
    encounters: 5, caches: 2,
    firstClear: { gold: 185, wood: 14, stone: 8, iron: 0, shards: 4, xp: 111 },
    replay: { gold: 74, wood: 7, stone: 4, iron: 0, shards: 2, xp: 47 },
    seasonRoute: { season: 'autumn', noteKey: 'stage.route.3' },
    ringSight: { ring: 'dawnward', noteKey: 'stage.sight.3' },
    durationMinutes: [4, 6],
  },
  {
    id: 4, region: 'farmland', nameKey: 'stage.4.name', objectiveKey: 'stage.4.objective',
    loreKey: 'stage.4.lore', bossKey: 'boss_greyfang', bossNameKey: 'boss.boss_greyfang.name', bossTestKey: 'stage.4.test',
    recommendedLevel: 4, chapterBoss: false,
    objective: { kind: 'explore', count: 3, labelKey: 'stage.4.objective' },
    enemies: ['warg', 'goblin_archer', 'orc_axe'],
    mapSeed: 1308, mapWidth: 49, mapHeight: 45,
    encounters: 5, caches: 2,
    firstClear: { gold: 220, wood: 16, stone: 10, iron: 0, shards: 5, xp: 145, ringId: 'windstep' },
    replay: { gold: 88, wood: 8, stone: 5, iron: 0, shards: 3, xp: 62 },
    seasonRoute: { season: 'winter', noteKey: 'stage.route.4' },
    durationMinutes: [4, 6],
  },
  {
    id: 5, region: 'farmland', nameKey: 'stage.5.name', objectiveKey: 'stage.5.objective',
    loreKey: 'stage.5.lore', bossKey: 'boss_mogrun', bossNameKey: 'boss.boss_mogrun.name', bossTestKey: 'stage.5.test',
    recommendedLevel: 5, chapterBoss: true,
    objective: { kind: 'light', count: 1, labelKey: 'stage.5.objective' },
    enemies: ['orc_raider', 'orc_axe', 'warg', 'goblin_archer'],
    mapSeed: 1385, mapWidth: 50, mapHeight: 46,
    encounters: 6, caches: 2,
    firstClear: { gold: 255, wood: 27, stone: 18, iron: 0, shards: 8, xp: 185, unlocksSlot: 'active2', talentPoints: 1 },
    replay: { gold: 102, wood: 14, stone: 9, iron: 0, shards: 5, xp: 78 },
    seasonRoute: { season: 'spring', noteKey: 'stage.route.5' },
    ringSight: { ring: 'ember', noteKey: 'stage.sight.5' },
    durationMinutes: [4, 6],
  },
  {
    id: 6, region: 'woodland', nameKey: 'stage.6.name', objectiveKey: 'stage.6.objective',
    loreKey: 'stage.6.lore', bossKey: 'boss_ssilka', bossNameKey: 'boss.boss_ssilka.name', bossTestKey: 'stage.6.test',
    recommendedLevel: 6, chapterBoss: false,
    objective: { kind: 'rescue', count: 3, labelKey: 'stage.6.objective' },
    enemies: ['spider_broodling', 'goblin_scout', 'spider_weaver'],
    mapSeed: 1462, mapWidth: 52, mapHeight: 47,
    encounters: 6, caches: 2,
    firstClear: { gold: 290, wood: 19, stone: 13, iron: 0, shards: 6, xp: 230, ringId: 'thornwake' },
    replay: { gold: 116, wood: 10, stone: 6, iron: 0, shards: 4, xp: 97 },
    seasonRoute: { season: 'spring', noteKey: 'stage.route.6' },
    durationMinutes: [4, 6],
  },
  {
    id: 7, region: 'woodland', nameKey: 'stage.7.name', objectiveKey: 'stage.7.objective',
    loreKey: 'stage.7.lore', bossKey: 'boss_briararcher', bossNameKey: 'boss.boss_briararcher.name', bossTestKey: 'stage.7.test',
    recommendedLevel: 7, chapterBoss: false,
    objective: { kind: 'recover', count: 1, labelKey: 'stage.7.objective' },
    enemies: ['goblin_archer', 'orc_raider', 'spider_broodling'],
    mapSeed: 1539, mapWidth: 53, mapHeight: 48,
    encounters: 6, caches: 3,
    firstClear: { gold: 325, wood: 21, stone: 15, iron: 0, shards: 7, xp: 280 },
    replay: { gold: 130, wood: 10, stone: 8, iron: 0, shards: 4, xp: 119 },
    seasonRoute: { season: 'autumn', noteKey: 'stage.route.7' },
    ringSight: { ring: 'dawnward', noteKey: 'stage.sight.7' },
    durationMinutes: [4, 6],
  },
  {
    id: 8, region: 'woodland', nameKey: 'stage.8.name', objectiveKey: 'stage.8.objective',
    loreKey: 'stage.8.lore', bossKey: 'boss_norgath', bossNameKey: 'boss.boss_norgath.name', bossTestKey: 'stage.8.test',
    recommendedLevel: 8, chapterBoss: false,
    objective: { kind: 'light', count: 3, labelKey: 'stage.8.objective' },
    enemies: ['spider_weaver', 'orc_shield', 'goblin_archer'],
    mapSeed: 1616, mapWidth: 54, mapHeight: 50,
    encounters: 7, caches: 3,
    firstClear: { gold: 360, wood: 23, stone: 17, iron: 9, shards: 8, xp: 336, ringId: 'dawnward' },
    replay: { gold: 144, wood: 12, stone: 8, iron: 4, shards: 5, xp: 142 },
    seasonRoute: { season: 'summer', noteKey: 'stage.route.8' },
    durationMinutes: [4, 6],
  },
  {
    id: 9, region: 'woodland', nameKey: 'stage.9.name', objectiveKey: 'stage.9.objective',
    loreKey: 'stage.9.lore', bossKey: 'boss_hushcaller', bossNameKey: 'boss.boss_hushcaller.name', bossTestKey: 'stage.9.test',
    recommendedLevel: 9, chapterBoss: false,
    objective: { kind: 'destroy', count: 4, labelKey: 'stage.9.objective' },
    enemies: ['barrow_wight', 'spider_broodling', 'orc_raider'],
    mapSeed: 1693, mapWidth: 56, mapHeight: 51,
    encounters: 7, caches: 3,
    firstClear: { gold: 395, wood: 24, stone: 19, iron: 10, shards: 9, xp: 396, ringId: 'venomcoil' },
    replay: { gold: 158, wood: 12, stone: 10, iron: 5, shards: 5, xp: 168 },
    seasonRoute: { season: 'autumn', noteKey: 'stage.route.9' },
    durationMinutes: [6, 9],
  },
  {
    id: 10, region: 'woodland', nameKey: 'stage.10.name', objectiveKey: 'stage.10.objective',
    loreKey: 'stage.10.lore', bossKey: 'boss_ashweb_queen', bossNameKey: 'boss.boss_ashweb_queen.name', bossTestKey: 'stage.10.test',
    recommendedLevel: 10, chapterBoss: true,
    objective: { kind: 'light', count: 1, labelKey: 'stage.10.objective' },
    enemies: ['spider_weaver', 'spider_broodling', 'orc_axe', 'goblin_archer'],
    mapSeed: 1770, mapWidth: 57, mapHeight: 52,
    encounters: 7, caches: 3,
    firstClear: { gold: 430, wood: 39, stone: 32, iron: 15, shards: 14, xp: 462, talentPoints: 1 },
    replay: { gold: 172, wood: 20, stone: 16, iron: 8, shards: 8, xp: 196 },
    seasonRoute: { season: 'winter', noteKey: 'stage.route.10' },
    ringSight: { ring: 'ember', noteKey: 'stage.sight.10' },
    durationMinutes: [6, 9],
  },
  {
    id: 11, region: 'mountain', nameKey: 'stage.11.name', objectiveKey: 'stage.11.objective',
    loreKey: 'stage.11.lore', bossKey: 'boss_rockjaw', bossNameKey: 'boss.boss_rockjaw.name', bossTestKey: 'stage.11.test',
    recommendedLevel: 11, chapterBoss: false,
    objective: { kind: 'collect', count: 5, labelKey: 'stage.11.objective' },
    enemies: ['orc_axe', 'orc_shield', 'goblin_sapper'],
    mapSeed: 1847, mapWidth: 58, mapHeight: 53,
    encounters: 8, caches: 3,
    firstClear: { gold: 465, wood: 28, stone: 23, iron: 11, shards: 10, xp: 534, ringId: 'frostwake' },
    replay: { gold: 186, wood: 14, stone: 12, iron: 6, shards: 6, xp: 226 },
    seasonRoute: { season: 'summer', noteKey: 'stage.route.11' },
    durationMinutes: [6, 9],
  },
  {
    id: 12, region: 'mountain', nameKey: 'stage.12.name', objectiveKey: 'stage.12.objective',
    loreKey: 'stage.12.lore', bossKey: 'boss_bragg', bossNameKey: 'boss.boss_bragg.name', bossTestKey: 'stage.12.test',
    recommendedLevel: 12, chapterBoss: false,
    objective: { kind: 'rescue', count: 1, labelKey: 'stage.12.objective' },
    enemies: ['orc_axe', 'troll', 'goblin_sapper'],
    mapSeed: 1924, mapWidth: 60, mapHeight: 54,
    encounters: 8, caches: 3,
    firstClear: { gold: 500, wood: 29, stone: 25, iron: 12, shards: 11, xp: 610, unlocksSlot: 'support1' },
    replay: { gold: 200, wood: 14, stone: 12, iron: 6, shards: 7, xp: 259 },
    seasonRoute: { season: 'winter', noteKey: 'stage.route.12' },
    ringSight: { ring: 'ember', noteKey: 'stage.sight.12' },
    durationMinutes: [6, 9],
  },
  {
    id: 13, region: 'mountain', nameKey: 'stage.13.name', objectiveKey: 'stage.13.objective',
    loreKey: 'stage.13.lore', bossKey: 'boss_whitefang', bossNameKey: 'boss.boss_whitefang.name', bossTestKey: 'stage.13.test',
    recommendedLevel: 13, chapterBoss: false,
    objective: { kind: 'explore', count: 3, labelKey: 'stage.13.objective' },
    enemies: ['warg', 'warg_alpha', 'orc_shield'],
    mapSeed: 2001, mapWidth: 61, mapHeight: 56,
    encounters: 8, caches: 3,
    firstClear: { gold: 535, wood: 31, stone: 27, iron: 13, shards: 12, xp: 692, ringId: 'iron_oath' },
    replay: { gold: 214, wood: 16, stone: 14, iron: 6, shards: 7, xp: 293 },
    seasonRoute: { season: 'winter', noteKey: 'stage.route.13' },
    ringSight: { ring: 'frostwake', noteKey: 'stage.sight.13' },
    durationMinutes: [6, 9],
  },
  {
    id: 14, region: 'mountain', nameKey: 'stage.14.name', objectiveKey: 'stage.14.objective',
    loreKey: 'stage.14.lore', bossKey: 'boss_ironecho', bossNameKey: 'boss.boss_ironecho.name', bossTestKey: 'stage.14.test',
    recommendedLevel: 14, chapterBoss: false,
    objective: { kind: 'recover', count: 3, labelKey: 'stage.14.objective' },
    enemies: ['troll', 'orc_shield', 'goblin_archer'],
    mapSeed: 2078, mapWidth: 62, mapHeight: 57,
    encounters: 9, caches: 4,
    firstClear: { gold: 570, wood: 33, stone: 29, iron: 14, shards: 12, xp: 779, ringId: 'echo' },
    replay: { gold: 228, wood: 16, stone: 14, iron: 7, shards: 7, xp: 330 },
    seasonRoute: { season: 'autumn', noteKey: 'stage.route.14' },
    durationMinutes: [6, 9],
  },
  {
    id: 15, region: 'mountain', nameKey: 'stage.15.name', objectiveKey: 'stage.15.objective',
    loreKey: 'stage.15.lore', bossKey: 'boss_durnok', bossNameKey: 'boss.boss_durnok.name', bossTestKey: 'stage.15.test',
    recommendedLevel: 15, chapterBoss: true,
    objective: { kind: 'light', count: 1, labelKey: 'stage.15.objective' },
    enemies: ['cave_troll', 'orc_axe', 'orc_shield', 'goblin_sapper'],
    mapSeed: 2155, mapWidth: 64, mapHeight: 58,
    encounters: 9, caches: 4,
    firstClear: { gold: 605, wood: 51, stone: 45, iron: 22, shards: 18, xp: 871, talentPoints: 1 },
    replay: { gold: 242, wood: 26, stone: 22, iron: 11, shards: 11, xp: 370 },
    seasonRoute: { season: 'spring', noteKey: 'stage.route.15' },
    ringSight: { ring: 'dawnward', noteKey: 'stage.sight.15' },
    durationMinutes: [6, 9],
  },
  {
    id: 16, region: 'borderland', nameKey: 'stage.16.name', objectiveKey: 'stage.16.objective',
    loreKey: 'stage.16.lore', bossKey: 'boss_karg', bossNameKey: 'boss.boss_karg.name', bossTestKey: 'stage.16.test',
    recommendedLevel: 16, chapterBoss: false,
    objective: { kind: 'escort', count: 3, labelKey: 'stage.16.objective' },
    enemies: ['uruk_soldier', 'uruk_crossbow', 'orc_shield'],
    mapSeed: 2232, mapWidth: 65, mapHeight: 59,
    encounters: 9, caches: 4,
    firstClear: { gold: 640, wood: 36, stone: 32, iron: 16, shards: 14, xp: 969 },
    replay: { gold: 256, wood: 18, stone: 16, iron: 8, shards: 8, xp: 411 },
    seasonRoute: { season: 'spring', noteKey: 'stage.route.16' },
    durationMinutes: [6, 9],
  },
  {
    id: 17, region: 'borderland', nameKey: 'stage.17.name', objectiveKey: 'stage.17.objective',
    loreKey: 'stage.17.lore', bossKey: 'boss_uzg', bossNameKey: 'boss.boss_uzg.name', bossTestKey: 'stage.17.test',
    recommendedLevel: 17, chapterBoss: false,
    objective: { kind: 'sabotage', count: 3, labelKey: 'stage.17.objective' },
    enemies: ['uruk_pikeman', 'uruk_crossbow', 'goblin_sapper'],
    mapSeed: 2309, mapWidth: 66, mapHeight: 60,
    encounters: 10, caches: 4,
    firstClear: { gold: 675, wood: 38, stone: 34, iron: 17, shards: 15, xp: 1072, ringId: 'stormcall' },
    replay: { gold: 270, wood: 19, stone: 17, iron: 8, shards: 9, xp: 455 },
    seasonRoute: { season: 'summer', noteKey: 'stage.route.17' },
    durationMinutes: [6, 9],
  },
  {
    id: 18, region: 'borderland', nameKey: 'stage.18.name', objectiveKey: 'stage.18.objective',
    loreKey: 'stage.18.lore', bossKey: 'boss_wardrummer', bossNameKey: 'boss.boss_wardrummer.name', bossTestKey: 'stage.18.test',
    recommendedLevel: 18, chapterBoss: false,
    objective: { kind: 'destroy', count: 4, labelKey: 'stage.18.objective' },
    enemies: ['uruk_soldier', 'marauder', 'uruk_pikeman', 'warg'],
    mapSeed: 2386, mapWidth: 67, mapHeight: 62,
    encounters: 10, caches: 4,
    firstClear: { gold: 710, wood: 40, stone: 36, iron: 18, shards: 16, xp: 1180 },
    replay: { gold: 284, wood: 20, stone: 18, iron: 9, shards: 10, xp: 501 },
    seasonRoute: { season: 'autumn', noteKey: 'stage.route.18' },
    ringSight: { ring: 'ember', noteKey: 'stage.sight.18' },
    durationMinutes: [6, 9],
  },
  {
    id: 19, region: 'borderland', nameKey: 'stage.19.name', objectiveKey: 'stage.19.objective',
    loreKey: 'stage.19.lore', bossKey: 'boss_cinderknight', bossNameKey: 'boss.boss_cinderknight.name', bossTestKey: 'stage.19.test',
    recommendedLevel: 19, chapterBoss: false,
    objective: { kind: 'light', count: 3, labelKey: 'stage.19.objective' },
    enemies: ['uruk_soldier', 'uruk_crossbow', 'marauder'],
    mapSeed: 2463, mapWidth: 69, mapHeight: 63,
    encounters: 10, caches: 4,
    firstClear: { gold: 745, wood: 41, stone: 38, iron: 19, shards: 16, xp: 1294 },
    replay: { gold: 298, wood: 20, stone: 19, iron: 10, shards: 10, xp: 549 },
    seasonRoute: { season: 'summer', noteKey: 'stage.route.19' },
    durationMinutes: [8, 12],
  },
  {
    id: 20, region: 'borderland', nameKey: 'stage.20.name', objectiveKey: 'stage.20.objective',
    loreKey: 'stage.20.lore', bossKey: 'boss_varzug', bossNameKey: 'boss.boss_varzug.name', bossTestKey: 'stage.20.test',
    recommendedLevel: 20, chapterBoss: true,
    objective: { kind: 'light', count: 1, labelKey: 'stage.20.objective' },
    enemies: ['uruk_soldier', 'uruk_pikeman', 'uruk_crossbow', 'warg_alpha'],
    mapSeed: 2540, mapWidth: 70, mapHeight: 64,
    encounters: 11, caches: 4,
    firstClear: { gold: 780, wood: 64, stone: 60, iron: 30, shards: 24, xp: 1412, unlocksSlot: 'support2', talentPoints: 1 },
    replay: { gold: 312, wood: 32, stone: 30, iron: 15, shards: 14, xp: 599 },
    seasonRoute: { season: 'winter', noteKey: 'stage.route.20' },
    durationMinutes: [8, 12],
  },
  {
    id: 21, region: 'winterland', nameKey: 'stage.21.name', objectiveKey: 'stage.21.objective',
    loreKey: 'stage.21.lore', bossKey: 'boss_glasswight', bossNameKey: 'boss.boss_glasswight.name', bossTestKey: 'stage.21.test',
    recommendedLevel: 21, chapterBoss: false,
    objective: { kind: 'recover', count: 1, labelKey: 'stage.21.objective' },
    enemies: ['barrow_wight', 'shade', 'frost_wight'],
    mapSeed: 2617, mapWidth: 71, mapHeight: 65,
    encounters: 11, caches: 5,
    firstClear: { gold: 815, wood: 45, stone: 42, iron: 21, shards: 18, xp: 1537, ringId: 'duskveil' },
    replay: { gold: 326, wood: 22, stone: 21, iron: 10, shards: 11, xp: 652 },
    seasonRoute: { season: 'winter', noteKey: 'stage.route.21' },
    ringSight: { ring: 'dawnward', noteKey: 'stage.sight.21' },
    durationMinutes: [8, 12],
  },
  {
    id: 22, region: 'winterland', nameKey: 'stage.22.name', objectiveKey: 'stage.22.objective',
    loreKey: 'stage.22.lore', bossKey: 'boss_riftkeeper', bossNameKey: 'boss.boss_riftkeeper.name', bossTestKey: 'stage.22.test',
    recommendedLevel: 22, chapterBoss: false,
    objective: { kind: 'explore', count: 3, labelKey: 'stage.22.objective' },
    enemies: ['shade', 'frost_wight', 'cave_troll'],
    mapSeed: 2694, mapWidth: 73, mapHeight: 66,
    encounters: 11, caches: 5,
    firstClear: { gold: 850, wood: 46, stone: 44, iron: 22, shards: 18, xp: 1666 },
    replay: { gold: 340, wood: 23, stone: 22, iron: 11, shards: 11, xp: 707 },
    seasonRoute: { season: 'autumn', noteKey: 'stage.route.22' },
    ringSight: { ring: 'frostwake', noteKey: 'stage.sight.22' },
    durationMinutes: [8, 12],
  },
  {
    id: 23, region: 'winterland', nameKey: 'stage.23.name', objectiveKey: 'stage.23.objective',
    loreKey: 'stage.23.lore', bossKey: 'boss_paleflame', bossNameKey: 'boss.boss_paleflame.name', bossTestKey: 'stage.23.test',
    recommendedLevel: 23, chapterBoss: false,
    objective: { kind: 'collect', count: 4, labelKey: 'stage.23.objective' },
    enemies: ['frost_wight', 'barrow_wight', 'warg_alpha'],
    mapSeed: 2771, mapWidth: 74, mapHeight: 68,
    encounters: 12, caches: 5,
    firstClear: { gold: 885, wood: 48, stone: 46, iron: 23, shards: 19, xp: 1801 },
    replay: { gold: 354, wood: 24, stone: 23, iron: 12, shards: 11, xp: 764 },
    seasonRoute: { season: 'winter', noteKey: 'stage.route.23' },
    ringSight: { ring: 'frostwake', noteKey: 'stage.sight.23' },
    durationMinutes: [8, 12],
  },
  {
    id: 24, region: 'winterland', nameKey: 'stage.24.name', objectiveKey: 'stage.24.objective',
    loreKey: 'stage.24.lore', bossKey: 'boss_oathbreaker', bossNameKey: 'boss.boss_oathbreaker.name', bossTestKey: 'stage.24.test',
    recommendedLevel: 24, chapterBoss: false,
    objective: { kind: 'defend', count: 3, labelKey: 'stage.24.objective' },
    enemies: ['cave_troll', 'shade', 'uruk_soldier'],
    mapSeed: 2848, mapWidth: 75, mapHeight: 69,
    encounters: 12, caches: 5,
    firstClear: { gold: 920, wood: 50, stone: 48, iron: 24, shards: 20, xp: 1940 },
    replay: { gold: 368, wood: 25, stone: 24, iron: 12, shards: 12, xp: 823 },
    seasonRoute: { season: 'spring', noteKey: 'stage.route.24' },
    durationMinutes: [8, 12],
  },
  {
    id: 25, region: 'winterland', nameKey: 'stage.25.name', objectiveKey: 'stage.25.objective',
    loreKey: 'stage.25.lore', bossKey: 'boss_nameless_nazgul', bossNameKey: 'boss.boss_nameless_nazgul.name', bossTestKey: 'stage.25.test',
    recommendedLevel: 25, chapterBoss: true,
    objective: { kind: 'light', count: 1, labelKey: 'stage.25.objective' },
    enemies: ['frost_wight', 'shade', 'barrow_wight', 'warg_alpha'],
    mapSeed: 2925, mapWidth: 76, mapHeight: 70,
    encounters: 12, caches: 5,
    firstClear: { gold: 955, wood: 78, stone: 75, iron: 38, shards: 29, xp: 2086, ringId: 'last_hearth', talentPoints: 1 },
    replay: { gold: 382, wood: 39, stone: 38, iron: 19, shards: 17, xp: 885 },
    seasonRoute: { season: 'winter', noteKey: 'stage.route.25' },
    ringSight: { ring: 'dawnward', noteKey: 'stage.sight.25' },
    durationMinutes: [8, 12],
  },
  {
    id: 26, region: 'fortress', nameKey: 'stage.26.name', objectiveKey: 'stage.26.objective',
    loreKey: 'stage.26.lore', bossKey: 'boss_gruk', bossNameKey: 'boss.boss_gruk.name', bossTestKey: 'stage.26.test',
    recommendedLevel: 26, chapterBoss: false,
    objective: { kind: 'sabotage', count: 4, labelKey: 'stage.26.objective' },
    enemies: ['goblin_sapper', 'uruk_soldier', 'ash_hound'],
    mapSeed: 3002, mapWidth: 78, mapHeight: 71,
    encounters: 13, caches: 5,
    firstClear: { gold: 990, wood: 53, stone: 51, iron: 26, shards: 22, xp: 2236 },
    replay: { gold: 396, wood: 26, stone: 26, iron: 13, shards: 13, xp: 949 },
    seasonRoute: { season: 'summer', noteKey: 'stage.route.26' },
    durationMinutes: [8, 12],
  },
  {
    id: 27, region: 'fortress', nameKey: 'stage.27.name', objectiveKey: 'stage.27.objective',
    loreKey: 'stage.27.lore', bossKey: 'boss_cindermaw', bossNameKey: 'boss.boss_cindermaw.name', bossTestKey: 'stage.27.test',
    recommendedLevel: 27, chapterBoss: false,
    objective: { kind: 'destroy', count: 4, labelKey: 'stage.27.objective' },
    enemies: ['ash_hound', 'uruk_soldier', 'cave_troll'],
    mapSeed: 3079, mapWidth: 79, mapHeight: 72,
    encounters: 13, caches: 5,
    firstClear: { gold: 1025, wood: 55, stone: 53, iron: 27, shards: 22, xp: 2392 },
    replay: { gold: 410, wood: 28, stone: 26, iron: 14, shards: 13, xp: 1015 },
    seasonRoute: { season: 'summer', noteKey: 'stage.route.27' },
    ringSight: { ring: 'ember', noteKey: 'stage.sight.27' },
    durationMinutes: [8, 12],
  },
  {
    id: 28, region: 'fortress', nameKey: 'stage.28.name', objectiveKey: 'stage.28.objective',
    loreKey: 'stage.28.lore', bossKey: 'boss_castellan', bossNameKey: 'boss.boss_castellan.name', bossTestKey: 'stage.28.test',
    recommendedLevel: 28, chapterBoss: false,
    objective: { kind: 'recover', count: 1, labelKey: 'stage.28.objective' },
    enemies: ['uruk_soldier', 'uruk_pikeman', 'shade', 'ash_hound'],
    mapSeed: 3156, mapWidth: 80, mapHeight: 74,
    encounters: 14, caches: 6,
    firstClear: { gold: 1060, wood: 57, stone: 55, iron: 28, shards: 23, xp: 2553 },
    replay: { gold: 424, wood: 28, stone: 28, iron: 14, shards: 14, xp: 1083 },
    seasonRoute: { season: 'autumn', noteKey: 'stage.route.28' },
    durationMinutes: [8, 12],
  },
  {
    id: 29, region: 'fortress', nameKey: 'stage.29.name', objectiveKey: 'stage.29.objective',
    loreKey: 'stage.29.lore', bossKey: 'boss_oaththief', bossNameKey: 'boss.boss_oaththief.name', bossTestKey: 'stage.29.test',
    recommendedLevel: 29, chapterBoss: false,
    objective: { kind: 'destroy', count: 3, labelKey: 'stage.29.objective' },
    enemies: ['shade', 'uruk_soldier', 'ash_hound', 'frost_wight'],
    mapSeed: 3233, mapWidth: 82, mapHeight: 75,
    encounters: 14, caches: 6,
    firstClear: { gold: 1095, wood: 58, stone: 57, iron: 29, shards: 24, xp: 2719 },
    replay: { gold: 438, wood: 29, stone: 28, iron: 14, shards: 14, xp: 1154 },
    seasonRoute: { season: 'spring', noteKey: 'stage.route.29' },
    ringSight: { ring: 'dawnward', noteKey: 'stage.sight.29' },
    durationMinutes: [8, 12],
  },
  {
    id: 30, region: 'fortress', nameKey: 'stage.30.name', objectiveKey: 'stage.30.objective',
    loreKey: 'stage.30.lore', bossKey: 'boss_ashen_regent', bossNameKey: 'boss.boss_ashen_regent.name', bossTestKey: 'stage.30.test',
    recommendedLevel: 30, chapterBoss: true,
    objective: { kind: 'light', count: 1, labelKey: 'stage.30.objective' },
    enemies: ['ash_hound', 'shade', 'uruk_soldier', 'cave_troll'],
    mapSeed: 3310, mapWidth: 83, mapHeight: 76,
    encounters: 14, caches: 6,
    firstClear: { gold: 1130, wood: 90, stone: 88, iron: 45, shards: 34, xp: 2891, talentPoints: 1 },
    replay: { gold: 452, wood: 45, stone: 44, iron: 22, shards: 20, xp: 1226 },
    seasonRoute: { season: 'winter', noteKey: 'stage.route.30' },
    durationMinutes: [8, 12],
  },
] as const;

export const STAGE_COUNT = STAGES.length;

export function stageById(id: number): StageDef | undefined {
  return STAGES.find((s) => s.id === id);
}

/** Chapter boundaries used by the campaign map and the six-boss gauntlet. */
export const CHAPTERS = [
  { id: 1, region: 'farmland' as const, stages: [1, 2, 3, 4, 5], nameKey: 'chapter.1.name', bossStage: 5 },
  { id: 2, region: 'woodland' as const, stages: [6, 7, 8, 9, 10], nameKey: 'chapter.2.name', bossStage: 10 },
  { id: 3, region: 'mountain' as const, stages: [11, 12, 13, 14, 15], nameKey: 'chapter.3.name', bossStage: 15 },
  { id: 4, region: 'borderland' as const, stages: [16, 17, 18, 19, 20], nameKey: 'chapter.4.name', bossStage: 20 },
  { id: 5, region: 'winterland' as const, stages: [21, 22, 23, 24, 25], nameKey: 'chapter.5.name', bossStage: 25 },
  { id: 6, region: 'fortress' as const, stages: [26, 27, 28, 29, 30], nameKey: 'chapter.6.name', bossStage: 30 },
] as const;

export function chapterForStage(stage: number) {
  return CHAPTERS.find((c) => (c.stages as readonly number[]).includes(stage))!;
}
